trhows an extremly dangerous error
```go
package main

import "fmt"

func main() {
	defer fmt.Println("Cleanup before exiting.") // Will still run

	fmt.Println("Before panic.")
	panic("Something went terribly wrong!") // Triggers a panic
	fmt.Println("After panic.") // This won't execute
}

```